languageCode = "en-us"
title = "mbentley.net"
baseurl = "https://www.mbentley.net/"
theme = "prologue"

[params]
  name = "Matt Bentley"
  description = "Sr. Solutions Engineer"
  copyright = "mbentley.net"

[[params.social]]
  medium = "github"
  icon = "github"
  link = "https://github.com/mbentley"

[[params.social]]
  medium = "linkedin"
  icon = "linkedin"
  link = "https://www.linkedin.com/in/matthewbbentley"

[[params.social]]
  medium = "facebook"
  icon = "facebook"
  link = "http://www.facebook.com/matthew.b.bentley"

[[params.social]]
  medium = "twitter"
  icon = "twitter"
  link = "https://twitter.com/matthewbentley"

#[[params.social]]
#  medium = "email"
#  icon = "envelope"
#  link = "mailto:mbentley@mbentley.net"

# Portfolio column one

#[[params.portfolio1]]
#  title = "Ipsum Feugiat"
#  alt = ""
#  source = "img/pic02.jpg"
#  url = "#"
#
#[[params.portfolio1]]
#  title = "Rhoncus Semper"
#  alt = ""
#  source = "img/pic03.jpg"
#  url = "#"
#
## Portfolio column two
#
#[[params.portfolio2]]
#  title = "Magna Nullam"
#  alt = ""
#  source = "img/pic04.jpg"
#  url = "#"
#
#[[params.portfolio2]]
#  title = "Natoque Vitae"
#  alt = ""
#  source = "img/pic05.jpg"
#  url = "#"
#
## Portfolio column 3
#
#[[params.portfolio3]]
#  title = "Dolor Penatibus"
#  alt = ""
#  source = "img/pic06.jpg"
#  url = "#"
#
#[[params.portfolio3]]
#  title = "Orci Convallis"
#  alt = ""
#  source = "img/pic07.jpg"
#  url = "#"
