languageCode = "en-us"
title = "mbentley.net"
baseurl = "https://www.mbentley.net/"
theme = "prologue"

[params]
  name = "Matt Bentley"
  description = "docker run mbentley/me"
  copyright = "mbentley.net"

[[params.social]]
  medium = "GitHub"
  icon = "fab fa-github"
  link = "https://github.com/mbentley"

[[params.social]]
  medium = "LinkedIn"
  icon = "fab fa-linkedin"
  link = "https://www.linkedin.com/in/matthewbbentley"

[[params.social]]
  medium = "Facebook"
  icon = "fab fa-facebook"
  link = "http://www.facebook.com/matthew.b.bentley"

[[params.social]]
  medium = "Twitter"
  icon = "fab fa-twitter"
  link = "https://twitter.com/matthewbentley"

[[params.social]]
  medium = "Mastodon"
  icon = "fab fa-mastodon"
  link = "https://mas.town/@mbentley"

[[params.social]]
  medium = "Blog"
  icon = "fas fa-blog"
  link = "https://blog.mbentley.net"
