languageCode = "en-us"
title = "mbentley.net"
baseurl = "https://www.mbentley.net/"
theme = "prologue"

[params]
  name = "Matt Bentley"
  description = "Solutions Engineer @ Docker"
  copyright = "mbentley.net"

[[params.social]]
  medium = "github"
  icon = "github"
  link = "https://github.com/mbentley"

[[params.social]]
  medium = "linkedin"
  icon = "linkedin"
  link = "https://www.linkedin.com/in/matthewbbentley"

[[params.social]]
  medium = "facebook"
  icon = "facebook"
  link = "http://www.facebook.com/matthew.b.bentley"

[[params.social]]
  medium = "twitter"
  icon = "twitter"
  link = "https://twitter.com/matthewbentley"

[[params.social]]
  medium = "blog"
  icon = "rss"
  link = "https://blog.mbentley.net"
